### ISSUE TITLE
CiroteMark tickdiff  inaccuracy.

### ISSUE THREAD

**Issue by naxeras** [MiSTer-devel/GBA_MiSTer#157]
In the Homebrew CiroteMark https://cirote3.itch.io/cirote3, tickdiff is -231276, on a real GBA is 0.

[https://i.ibb.co/mCmZqgzn/Whats-App-Image-2025-02-17-at-20-47-34.jpg](url)

Regards.

**Comment by wwark** [comment]
Hi,
Is the issue remains with accuracy core https://github.com/MiSTer-devel/GBA_MiSTer/tree/accuracy/releases ?
Thanks,

**Comment by birdybro** [comment]
It's some cringy hentai homebrew trash game, I guess I'll take one for the team and test it with the accuracy core...

**Comment by birdybro** [comment]
a![Image](https://github.com/user-attachments/assets/a3556876-131e-4622-86d9-9308fa62203a)

Robert, don't waste your time testing this, it's disgusting and really gross. Maybe someone who isn't a perverted 15 year old incel will code something that test this the same and doesn't throw disgusting images all over the screen in flashes.

All the other emulators are all over the place on this too, so I am doubting the accuracy of this test and don't even know what it is supposed to be testing.

**Comment by naxeras** [comment]
The test may be unpleasant for some, but it's useful for measuring core accuracy.
Since this test was released, some emulators have been updated and achieved perfect scores, such as Messen and Blizhawk.

https://emulation.gametechwiki.com/index.php/GBA_Tests

In addition, by fixing the test, timing issues in other games have been fixed.

**Comment by birdybro** [comment]
It's basically unpleasant for anyone who doesn't enjoy staring at goatse for extended periods of time -_-

**Comment by RobertPeip** [comment]
No, this test is not useful.
It's just a demo that probably checks the timer after some endless time (218 million clock ticks!)

There is no intermediate result, so how is anyone supposed to know where some difference comes from?

A good test is:
- open source
- short
- provides information what failed

This test does nothing of that.

Alyosha and Mesen did not fix this test really, they fixed other tests instead.
(https://github.com/alyosha-tas/GBAHawk/issues/54)

So if I have time, I would 100% work on Alyoshas tests instead.
(already started with one of them recently)

**Comment by naxeras** [comment]
> No, this test is not useful. It's just a demo that probably checks the timer after some endless time (218 million clock ticks!)
> 
> There is no intermediate result, so how is anyone supposed to know where some difference comes from?
> 
> A good test is:
> 
> * open source
> * short
> * provides information what failed
> 
> This test does nothing of that.
> 
> Alyosha and Mesen did not fix this test really, they fixed other tests instead. ([alyosha-tas/GBAHawk#54](https://github.com/alyosha-tas/GBAHawk/issues/54))
> 
> So if I have time, I would 100% work on Alyoshas tests instead. (already started with one of them recently)

I may have misinterpreted this post by Alyoshas

He posted "Right now the big driver for accuracy improvements is an (NSFW) test rom called CiroteMark."

https://tasvideos.org/Forum/Topics/23529?CurrentPage=4&Highlight=536079#536079

It may not help you improve, but it's clear that getting a score of 0 makes the core more accurate.

If you have other more useful tests, great.

If it helps here I have seen the discussion and commits to fix it:

https://forums.nesdev.org/viewtopic.php?p=301827#p301827
https://forums.nesdev.org/viewtopic.php?p=301900#p301900
https://github.com/SourMesen/Mesen2/commit/386ecc2fbdf32b490b552d724aa4b6b84e708fa1
https://github.com/SourMesen/Mesen2/commit/bbd9ed702d1c1b02e970a6c88ea40a4a8fddd075
https://github.com/SourMesen/Mesen2/commit/ad2b8b8895ec3685520dee3fa804aee5bca2ea09

Thanks for your great work Robert

**Comment by RobertPeip** [comment]
It helped them with motivation, which is perfectly fine.
Several testroms have been made to reach this goal, so it should be much easier for anyone else to also reach it in future :)

**Comment by naxeras** [comment]
> It helped them with motivation, which is perfectly fine. Several testroms have been made to reach this goal, so it should be much easier for anyone else to also reach it in future :)

I'm sure you'll eventually fine-tune the core, and it will pass any test out there. I have no doubt we'll have a much better GBA implementation than Analogue. You're truly a great talent.

Thanks for your hard work, Robert.
